# Generated by Django 5.2.5 on 2025-09-06 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFoundingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('current_level_of_study', models.CharField(choices=[('ug_1', 'Undergraduate - First Year'), ('ug_2', 'Undergraduate - Second Year'), ('ug_3', 'Undergraduate - Third Year'), ('ug_4', 'Undergraduate - Fourth Year'), ('pg_masters', 'Postgraduate - Masters'), ('pg_doctoral', 'Postgraduate - Doctoral'), ('other', 'Other')], max_length=100)),
                ('discipline', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('proof_of_association', models.FileField(upload_to='proofs/')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_founding_member', to='smile_forms.contact')),
            ],
        ),
    ]
