# Generated by Django 5.2.5 on 2025-09-06 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_forms', '0003_alter_foundingmember_proof_of_association_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfoundingmember',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_founding_member', to='smile_forms.contact'),
        ),
        migrations.AlterField(
            model_name='customfoundingmember',
            name='current_level_of_study',
            field=models.CharField(blank=True, choices=[('ug_1', 'Undergraduate - First Year'), ('ug_2', 'Undergraduate - Second Year'), ('ug_3', 'Undergraduate - Third Year'), ('ug_4', 'Undergraduate - Fourth Year'), ('pg_masters', 'Postgraduate - Masters'), ('pg_doctoral', 'Postgraduate - Doctoral'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customfoundingmember',
            name='discipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customfoundingmember',
            name='proof_of_association',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='customfoundingmember',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='customfoundingmember',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='foundingmember',
            name='proof_of_association',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='foundingmember',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
