# Generated by Django 5.2.5 on 2025-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_forms', '0004_alter_customfoundingmember_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitychapter',
            name='custom_founding_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='university_chapters', to='smile_forms.customfoundingmember'),
        ),
    ]
