# Generated by Django 5.2.5 on 2025-09-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_forms', '0005_universitychapter_custom_founding_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundingmember',
            name='proof_of_association',
            field=models.FileField(upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='foundingmember',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
