# Generated by Django 5.2.5 on 2025-09-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smile_forms', '0006_alter_foundingmember_proof_of_association_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitychapter',
            name='custom_founding_members',
            field=models.ManyToManyField(blank=True, related_name='university_chapters', to='smile_forms.customfoundingmember'),
        ),
    ]
